-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\cic_top_v0\cic_top_v0.vhd
-- Created: 2024-06-26 11:24:34
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- clk_decimated        0.2
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- output                          clk_decimated        0.2
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: cic_top_v0
-- Source Path: cic_top_v0
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity cic_top_v0 is
  port( clk                               :   in    std_logic;
        reset                             :   in    std_logic;
        clk_enable                        :   in    std_logic;
        input                             :   in    std_logic_vector(7 downto 0);  -- int8
        clk_decimated                     :   out   std_logic;
        output                            :   out   std_logic_vector(29 downto 0)  -- sfix30
        );
end cic_top_v0;


architecture rtl of cic_top_v0 is

  -- Component Declarations
  component cic_core_v0
    port( clk                             :   in    std_logic;
          enb_1_1_1                       :   in    std_logic;
          reset                           :   in    std_logic;
          CIC_Decimation1_in              :   in    std_logic_vector(7 downto 0);  -- int8
          ck_dec                          :   out    std_logic;
          CIC_Decimation1_out             :   out   std_logic_vector(29 downto 0)  -- sfix30
          );
  end component;

  -- Component Configuration Statements
  for all : cic_core_v0
    use entity work.cic_core_v0(rtl);

  -- Signals
  signal enb_1_1_1                        : std_logic;
  signal ck_dec                        : std_logic;
  signal CIC_Decimation1_out1             : std_logic_vector(29 downto 0);  -- ufix30

begin
  core_v0 : cic_core_v0
    port map( clk => clk,
              enb_1_1_1 => enb_1_1_1,
              reset => reset,
              ck_dec => ck_dec,
              CIC_Decimation1_in => input,  -- int8
              CIC_Decimation1_out => CIC_Decimation1_out1  -- sfix30
              );

  enb_1_1_1 <= clk_enable;
  clk_decimated <= ck_dec;
  output <= CIC_Decimation1_out1;

end rtl;

